// Products
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const REQUEST_ADD_PRODUCT = "REQUEST_ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const REQUEST_REMOVE_PRODUCT = "REQUEST_REMOVE_PRODUCT";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";